### ISSUE TITLE
Add more simulators 

### ISSUE THREAD

**Issue by junnmm** [kcc-community/hive#5]
Add more simulators 

- [x] @newgoo #6
- [x] @junnmm  #7
- [x] @junnmm  #8
- [x] @0xcary #9
- [x] @0xcary #10
- [x] @junnmm  #11
- [x] @0xcary #12
- [x] @newgoo #13
- [x] #14
- [x] @junnmm  #15
- [ ] @junnmm  #16 (use testnet in hive)
- [x] @junnmm  #17
- [x] @newgoo  #18
- [x] @newgoo(⚠️  Spend at least 1M gas) #19  
- [x] @Carry (⚠️  Spend at least 1M gas) #19
